Feature/feature add web form
Belatrya/Wordle pull request #22
Opened 2022-07-26 11:34 UTC by Belatrya

2022-07-26 13:43 UTC, DanilKozlov00 requested changes
- [ ] Reviewed

2022-07-26 13:43 UTC, DanilKozlov00 commented on src/main/java/config/ConfigurationContext.java
> +        return new DictionaryFileStorage(resource.getURI());
Два одинаковых метода, лишь с разными путями. Как решение вынести то что внутри в отдельный метод, принимающий путь. И внутри бинов возвращать результат этого метода

2022-07-26 13:43 UTC, DanilKozlov00 commented on src/main/java/controller/WordleController.java
> +    }
Не уверен, что корректно, помещать эти классы внутрь контроллера. Принцип единственной ответственности нарушается. Контроллер почему то знает про слова, хотя его задача это принимать и отправлять запросы.

2022-07-26 13:43 UTC, DanilKozlov00 commented on src/main/java/controller/WordleController.java
> +    }
Тоже единственная ответственность нарушена, контроллер не должен заниматься определением положения букв. Должен лишь получать эти буквы и отправлять результат проверки выполненный в другом классе.

2022-07-26 13:43 UTC, DanilKozlov00 commented on src/main/java/config/ConfigurationContext.java
> +@ComponentScan({"base", "model", "controller"})
Так, конечно, можно, но в случае масштабирования проекта тут будет 10+ папок прописанных ручками. 
Лучше вынести все пакеты в один большой, обычно это com.example или org.example. И тут писать уже его

2022-07-27 20:38 UTC, Belatrya commented on src/main/java/config/ConfigurationContext.java
> +@ComponentScan({"base", "model", "controller"})
будет сделано в отдельной ветке

2022-07-28 10:20 UTC, DanilKozlov00 approved these changes
- [ ] Reviewed

2022-07-28 10:22 UTC, Belatrya commented on run.bat
> +set CATALINA_HOME=%1
да, хорошая идея, спасибо

2022-07-28 10:38 UTC, merged